[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate"
]

[start]
cmd = "gunicorn backend.wsgi:application --config gunicorn.conf.py" 