# Generated by Django 5.1.3 on 2025-06-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donationmethod_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show this ministry on the global website'),
        ),
    ]
