# Generated by Django 5.1.3 on 2025-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ministry_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='shop_url',
            field=models.URLField(blank=True, help_text="Link to church's online store (e.g., Payhip store URL)", null=True),
        ),
    ]
