# Generated by Django 5.1.3 on 2025-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_church_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='global_feature_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Approval status for global feature request', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_global_featured',
            field=models.BooleanField(default=False, help_text='Show this event on the global site if approved'),
        ),
        migrations.AddField(
            model_name='hero',
            name='global_feature_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Approval status for global feature request', max_length=20),
        ),
        migrations.AddField(
            model_name='hero',
            name='is_global_featured',
            field=models.BooleanField(default=False, help_text='Show this hero on the global site if approved'),
        ),
        migrations.AddField(
            model_name='news',
            name='global_feature_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Approval status for global feature request', max_length=20),
        ),
        migrations.AddField(
            model_name='news',
            name='is_global_featured',
            field=models.BooleanField(default=False, help_text='Show this news on the global site if approved'),
        ),
    ]
