# Generated by Django 5.1.3 on 2025-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_global_feature_status_event_is_global_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalHero',
            fields=[
            ],
            options={
                'verbose_name': 'Local Hero',
                'verbose_name_plural': 'Local Heroes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.hero',),
        ),
    ]
