# Generated by Django 5.1.3 on 2025-06-30 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hero_global_feature_date_globalfeaturerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(help_text='Your name (can be anonymous)', max_length=100)),
                ('author_email', models.EmailField(help_text='Your email (will not be displayed publicly)', max_length=254)),
                ('title', models.CharField(help_text='Brief title for your testimony', max_length=200)),
                ('content', models.TextField(help_text='Share your testimony here')),
                ('location', models.CharField(blank=True, help_text='City, Country (optional)', max_length=100)),
                ('category', models.CharField(choices=[('salvation', 'Salvation Story'), ('healing', 'Healing'), ('deliverance', 'Deliverance'), ('blessing', 'Blessing'), ('ministry', 'Ministry Impact'), ('family', 'Family'), ('other', 'Other')], default='other', max_length=50)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval required before publishing')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide author name when displaying')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
        ),
    ]
