# Generated by Django 5.1.3 on 2025-06-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Leadership', max_length=200)),
                ('intro', models.TextField(blank=True, verbose_name='Introduction')),
                ('current_leadership', models.TextField(blank=True, verbose_name='Current Leadership')),
                ('board_members', models.TextField(blank=True, verbose_name='Board Members')),
                ('leadership_team', models.TextField(blank=True, verbose_name='Leadership Team')),
                ('vision_statement', models.TextField(blank=True, verbose_name='Vision Statement')),
                ('mission_statement', models.TextField(blank=True, verbose_name='Mission Statement')),
                ('chairman_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('board_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Page',
                'verbose_name_plural': 'Leadership Page',
            },
        ),
    ]
