# Generated by Django 5.1.3 on 2025-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_leadershippage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershippage',
            name='leadership_photo_1',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 1', null=True, upload_to='leadership/'),
        ),
        migrations.AddField(
            model_name='leadershippage',
            name='leadership_photo_2',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 2', null=True, upload_to='leadership/'),
        ),
        migrations.AddField(
            model_name='leadershippage',
            name='leadership_photo_3',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 3', null=True, upload_to='leadership/'),
        ),
        migrations.AddField(
            model_name='leadershippage',
            name='vice_chairman_image',
            field=models.ImageField(blank=True, help_text='Photo of the Vice Chairman', null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='board_image',
            field=models.ImageField(blank=True, help_text='Group photo of board members', null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='chairman_image',
            field=models.ImageField(blank=True, help_text='Photo of the Chairman', null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='team_image',
            field=models.ImageField(blank=True, help_text='Group photo of leadership team', null=True, upload_to='leadership/'),
        ),
    ]
