# Generated by Django 5.1.3 on 2025-06-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_leadershippage_leadership_photo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLeadershipPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Leadership', max_length=200)),
                ('intro', models.TextField(blank=True, verbose_name='Introduction')),
                ('current_leadership', models.TextField(blank=True, verbose_name='Current Leadership')),
                ('board_members', models.TextField(blank=True, verbose_name='Board Members')),
                ('leadership_team', models.TextField(blank=True, verbose_name='Leadership Team')),
                ('vision_statement', models.TextField(blank=True, verbose_name='Vision Statement')),
                ('mission_statement', models.TextField(blank=True, verbose_name='Mission Statement')),
                ('pastor_image', models.ImageField(blank=True, help_text='Photo of the Pastor', null=True, upload_to='leadership/local/')),
                ('assistant_pastor_image', models.ImageField(blank=True, help_text='Photo of the Assistant Pastor', null=True, upload_to='leadership/local/')),
                ('board_image', models.ImageField(blank=True, help_text='Group photo of board members', null=True, upload_to='leadership/local/')),
                ('team_image', models.ImageField(blank=True, help_text='Group photo of leadership team', null=True, upload_to='leadership/local/')),
                ('leadership_photo_1', models.ImageField(blank=True, help_text='Additional leadership photo 1', null=True, upload_to='leadership/local/')),
                ('leadership_photo_2', models.ImageField(blank=True, help_text='Additional leadership photo 2', null=True, upload_to='leadership/local/')),
                ('leadership_photo_3', models.ImageField(blank=True, help_text='Additional leadership photo 3', null=True, upload_to='leadership/local/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_page', to='core.church')),
            ],
            options={
                'verbose_name': 'Local Leadership Page',
                'verbose_name_plural': 'Local Leadership Pages',
            },
        ),
    ]
