# Generated by Django 5.1.3 on 2025-06-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_localleadershippage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('intro', models.TextField(blank=True, verbose_name='Intro/Mission')),
                ('founding_story', models.TextField(blank=True, verbose_name='Founding Story')),
                ('timeline', models.TextField(blank=True, verbose_name='Timeline')),
                ('leadership_timeline', models.TextField(blank=True, verbose_name='Leadership Timeline')),
                ('ministry_today', models.TextField(blank=True, verbose_name='Ministry Today')),
                ('quick_facts', models.TextField(blank=True, verbose_name='Quick Facts')),
                ('logo', models.ImageField(blank=True, help_text='Church logo', null=True, upload_to='about/local/')),
                ('founder_image', models.ImageField(blank=True, help_text='Photo of church founder or pastor', null=True, upload_to='about/local/')),
                ('extra_image', models.ImageField(blank=True, help_text='Additional church photo', null=True, upload_to='about/local/')),
                ('about_photo_1', models.ImageField(blank=True, help_text='Additional about page photo 1', null=True, upload_to='about/local/')),
                ('about_photo_2', models.ImageField(blank=True, help_text='Additional about page photo 2', null=True, upload_to='about/local/')),
                ('about_photo_3', models.ImageField(blank=True, help_text='Additional about page photo 3', null=True, upload_to='about/local/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_page', to='core.church')),
            ],
            options={
                'verbose_name': 'Local About Page',
                'verbose_name_plural': 'Local About Pages',
            },
        ),
    ]
