# Generated by Django 5.1.3 on 2025-07-01 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ministryjoinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField(help_text='Year of the event')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_highlights/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True)),
                ('attendees_count', models.IntegerField(blank=True, null=True)),
                ('testimonial', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.event')),
            ],
            options={
                'verbose_name': 'Event Highlight',
                'verbose_name_plural': 'Event Highlights',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.church')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registration_date'],
            },
        ),
    ]
