# Generated by Django 5.1.3 on 2025-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_eventhighlight_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_big_event',
            field=models.BooleanField(default=False, help_text='Use special big event template for this event'),
        ),
    ]
