# Generated by Django 5.1.3 on 2025-07-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_eventspeaker_eventscheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Optional hero/background video for this event.', null=True, upload_to='events/videos/'),
        ),
    ]
