# Generated by Django 5.1.3 on 2025-07-05 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_hero_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('media_file', models.FileField(help_text='Image or video file for hero slideshow', upload_to='hero/media/')),
                ('title', models.CharField(blank=True, help_text='Optional title for this media', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('order', models.IntegerField(default=1, help_text='Display order (1 = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_media', to='core.church')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_media', to='core.event')),
            ],
            options={
                'verbose_name': 'Hero Media',
                'verbose_name_plural': 'Hero Media',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
