# Generated by Django 5.1.3 on 2025-07-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_heromedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromedia',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_media', to='core.hero'),
        ),
    ]
