# Generated by Django 5.1.3 on 2025-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_heromedia_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_qr_code',
            field=models.BooleanField(default=False, help_text='Show QR code for this event on the detail page.'),
        ),
        migrations.DeleteModel(
            name='HeroMedia',
        ),
    ]
