# Generated by Django 5.1.3 on 2025-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_event_show_qr_code_delete_heromedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlight',
            name='video_url',
            field=models.URLField(blank=True, help_text='If a video is provided, it will be shown as the main media for this highlight. Otherwise, the image will be used. Enter a YouTube or Vimeo URL.', null=True),
        ),
    ]
