# Generated by Django 5.1.3 on 2025-07-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_eventhighlight_video_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConventionRegistration',
        ),
    ]
