# Generated by Django 5.1.3 on 2025-07-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_eventheromedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hero_video',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
