# Generated by Django 5.1.3 on 2025-07-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_event_hero_video_remove_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('video', models.FileField(blank=True, null=True, upload_to='hero/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_media', to='core.hero')),
            ],
            options={
                'verbose_name': 'Hero Media',
                'verbose_name_plural': 'Hero Media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
