# Generated by Django 5.1.3 on 2025-07-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_heromedia_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
