# Generated by Django 5.1.3 on 2025-07-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fix_website_field_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heromedia',
            name='church',
        ),
    ]
