# Generated by Django 5.1.3 on 2025-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_heromedia_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='extra_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='founder_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='church',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='churches/banners/'),
        ),
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='churches/logos/'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='conventions/'),
        ),
        migrations.AlterField(
            model_name='eventheromedia',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='eventheromedia',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='hero/videos/'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='event_highlights/'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='events/speakers/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='background_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='background_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='hero/videos/'),
        ),
        migrations.AlterField(
            model_name='heromedia',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heromedia',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='hero/videos/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='board_image',
            field=models.ImageField(blank=True, help_text='Group photo of board members', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='chairman_image',
            field=models.ImageField(blank=True, help_text='Photo of the Chairman', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='leadership_photo_1',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 1', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='leadership_photo_2',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 2', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='leadership_photo_3',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 3', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='team_image',
            field=models.ImageField(blank=True, help_text='Group photo of leadership team', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='leadershippage',
            name='vice_chairman_image',
            field=models.ImageField(blank=True, help_text='Photo of the Vice Chairman', max_length=500, null=True, upload_to='leadership/'),
        ),
        migrations.AlterField(
            model_name='localaboutpage',
            name='about_photo_1',
            field=models.ImageField(blank=True, help_text='Additional about page photo 1', max_length=500, null=True, upload_to='about/local/'),
        ),
        migrations.AlterField(
            model_name='localaboutpage',
            name='about_photo_2',
            field=models.ImageField(blank=True, help_text='Additional about page photo 2', max_length=500, null=True, upload_to='about/local/'),
        ),
        migrations.AlterField(
            model_name='localaboutpage',
            name='about_photo_3',
            field=models.ImageField(blank=True, help_text='Additional about page photo 3', max_length=500, null=True, upload_to='about/local/'),
        ),
        migrations.AlterField(
            model_name='localaboutpage',
            name='extra_image',
            field=models.ImageField(blank=True, help_text='Additional church photo', max_length=500, null=True, upload_to='about/local/'),
        ),
        migrations.AlterField(
            model_name='localaboutpage',
            name='founder_image',
            field=models.ImageField(blank=True, help_text='Photo of church founder or pastor', max_length=500, null=True, upload_to='about/local/'),
        ),
        migrations.AlterField(
            model_name='localaboutpage',
            name='logo',
            field=models.ImageField(blank=True, help_text='Church logo', max_length=500, null=True, upload_to='about/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='assistant_pastor_image',
            field=models.ImageField(blank=True, help_text='Photo of the Assistant Pastor', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='board_image',
            field=models.ImageField(blank=True, help_text='Group photo of board members', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='leadership_photo_1',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 1', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='leadership_photo_2',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 2', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='leadership_photo_3',
            field=models.ImageField(blank=True, help_text='Additional leadership photo 3', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='pastor_image',
            field=models.ImageField(blank=True, help_text='Photo of the Pastor', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='localleadershippage',
            name='team_image',
            field=models.ImageField(blank=True, help_text='Group photo of leadership team', max_length=500, null=True, upload_to='leadership/local/'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='ministries/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='sermons/audio/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='sermons/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='sermons/video/'),
        ),
    ]
