# Generated by Django 5.1.3 on 2025-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_aboutpage_extra_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='nav_logo',
            field=models.ImageField(blank=True, help_text='Logo specifically for navigation bar (small, circular)', max_length=500, null=True, upload_to='churches/nav_logos/'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_active'], name='core_church_is_acti_50cdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_approved'], name='core_church_is_appr_536820_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_featured'], name='core_church_is_feat_4b79b5_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['city', 'country'], name='core_church_city_ae8316_idx'),
        ),
    ]
