# Generated by Django 5.1.3 on 2025-07-24 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_church_nav_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('global_nav_logo', models.ImageField(blank=True, help_text='Global navigation logo that appears on all church pages', max_length=500, null=True, upload_to='global/nav_logos/')),
                ('site_name', models.CharField(default='Bethel Prayer Ministry International', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='Global site description')),
                ('global_contact_email', models.EmailField(blank=True, max_length=254)),
                ('global_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
