# Generated by Django 5.1.3 on 2025-07-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='local_church_redirect_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic redirect to nearest church based on user location'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='local_church_redirect_max_distance_km',
            field=models.IntegerField(default=50, help_text='Maximum distance in kilometers for church redirect (when coordinates are available)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='local_church_redirect_min_score',
            field=models.IntegerField(default=100, help_text='Minimum score required for church redirect (50=country match, 100=partial city, 200=exact city)'),
        ),
    ]
