# Generated by Django 5.1.3 on 2025-08-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_church_friday_service_church_other_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='main_global_church',
            field=models.ForeignKey(blank=True, help_text='Main global church to redirect to when no local church is found', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.church'),
        ),
    ]
