# Generated by Django 5.1.3 on 2025-08-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_globalsettings_main_global_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='global_hero',
            field=models.ForeignKey(blank=True, help_text='Global hero banner to display on the main global site homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hero'),
        ),
    ]
