# Generated by Django 5.1.3 on 2025-08-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_globalsettings_global_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='global_hero_fallback_enabled',
            field=models.BooleanField(default=True, help_text='Show fallback hero if selected hero is inactive'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='global_hero_rotation_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic rotation of multiple global heroes'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='global_hero_rotation_interval',
            field=models.IntegerField(default=5, help_text='Rotation interval in seconds (minimum 3 seconds)'),
        ),
    ]
