# Generated by Django 5.1.3 on 2025-08-04 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_global_hero_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Your name (can be anonymous)', max_length=100)),
                ('email', models.EmailField(help_text='Your email (will not be displayed publicly)', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('title', models.CharField(help_text='Brief title for your prayer request', max_length=200)),
                ('request', models.TextField(help_text='Share your prayer request here')),
                ('category', models.CharField(choices=[('health', 'Health & Healing'), ('family', 'Family'), ('financial', 'Financial'), ('spiritual', 'Spiritual Growth'), ('relationships', 'Relationships'), ('work', 'Work/Career'), ('other', 'Other')], default='other', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide name when displaying')),
                ('is_public', models.BooleanField(default=True, help_text='Allow others to see and pray for this request')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval required before publishing')),
                ('is_answered', models.BooleanField(default=False, help_text='Mark as answered when prayer is fulfilled')),
                ('answered_date', models.DateTimeField(blank=True, null=True)),
                ('answer_notes', models.TextField(blank=True, help_text='Notes about how the prayer was answered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church')),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
