# Generated by Django 5.1.3 on 2025-08-04 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_prayerrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('subject', models.CharField(help_text='Subject of your message', max_length=200)),
                ('message', models.TextField(help_text='Your message')),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('prayer', 'Prayer Request'), ('donation', 'Donation Question'), ('event', 'Event Information'), ('ministry', 'Ministry Question'), ('technical', 'Technical Support'), ('other', 'Other')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read when reviewed')),
                ('is_replied', models.BooleanField(default=False, help_text='Mark as replied when responded to')),
                ('reply_message', models.TextField(blank=True, help_text='Admin reply to the user')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStreamSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube Live'), ('facebook', 'Facebook Live'), ('instagram', 'Instagram Live'), ('zoom', 'Zoom'), ('other', 'Other')], default='youtube', help_text='Choose your live streaming platform', max_length=20)),
                ('youtube_channel_id', models.CharField(blank=True, help_text='Your YouTube channel ID', max_length=100)),
                ('youtube_stream_key', models.CharField(blank=True, help_text='YouTube stream key (keep private)', max_length=200)),
                ('youtube_live_url', models.URLField(blank=True, help_text='Your YouTube live stream URL')),
                ('facebook_page_id', models.CharField(blank=True, help_text='Your Facebook page ID', max_length=100)),
                ('facebook_live_url', models.URLField(blank=True, help_text='Your Facebook live stream URL')),
                ('is_live', models.BooleanField(default=False, help_text="Check when you're currently live streaming")),
                ('stream_title', models.CharField(blank=True, help_text='Title of your current live stream', max_length=200)),
                ('stream_description', models.TextField(blank=True, help_text='Description of your live stream')),
                ('sunday_morning_time', models.TimeField(default='09:00', help_text='Sunday morning service time')),
                ('sunday_evening_time', models.TimeField(default='18:00', help_text='Sunday evening service time')),
                ('wednesday_time', models.TimeField(default='19:00', help_text='Wednesday service time')),
                ('friday_time', models.TimeField(default='18:00', help_text='Friday service time')),
                ('auto_detect_live', models.BooleanField(default=True, help_text='Automatically detect when live based on schedule')),
                ('notify_congregation', models.BooleanField(default=True, help_text='Send notifications when going live')),
                ('enable_chat', models.BooleanField(default=True, help_text='Enable live chat during streams')),
                ('moderate_chat', models.BooleanField(default=True, help_text='Moderate chat messages')),
                ('embed_width', models.IntegerField(default=100, help_text='Embed width percentage')),
                ('embed_height', models.IntegerField(default=400, help_text='Embed height in pixels')),
                ('autoplay', models.BooleanField(default=True, help_text='Autoplay live stream when page loads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.church')),
            ],
            options={
                'verbose_name': 'Live Stream Settings',
                'verbose_name_plural': 'Live Stream Settings',
            },
        ),
    ]
