# Generated by Django 5.1.3 on 2025-08-12 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_contactmessage_livestreamsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_tracking', models.BooleanField(default=True, help_text='Enable visitor tracking')),
                ('track_geolocation', models.BooleanField(default=True, help_text='Track country/city from IP')),
                ('track_user_agent', models.BooleanField(default=True, help_text='Track browser/device info')),
                ('track_referrers', models.BooleanField(default=True, help_text='Track where visitors came from')),
                ('anonymize_ips', models.BooleanField(default=True, help_text='Anonymize IP addresses')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Days to keep analytics data')),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='Number of records to process in batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Settings',
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Django session ID', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text="Visitor's IP address")),
                ('user_agent', models.TextField(help_text='Browser/device information')),
                ('country', models.CharField(blank=True, help_text='Country from IP', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City from IP', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Region/State from IP', max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='other', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser name', max_length=50)),
                ('browser_version', models.CharField(blank=True, help_text='Browser version', max_length=20)),
                ('os', models.CharField(blank=True, help_text='Operating system', max_length=50)),
                ('referrer', models.URLField(blank=True, help_text='Where visitor came from')),
                ('referrer_domain', models.CharField(blank=True, help_text='Domain of referrer', max_length=200)),
                ('page_views_count', models.PositiveIntegerField(default=0, help_text='Number of pages viewed in this session')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Session duration in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When session started')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity in session')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session ended', null=True)),
                ('church', models.ForeignKey(blank=True, help_text='Church context if visiting church page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.church')),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Full URL visited')),
                ('path', models.CharField(help_text='URL path', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='Page title', max_length=200)),
                ('view_name', models.CharField(blank=True, help_text='Django view name', max_length=100)),
                ('load_time', models.PositiveIntegerField(blank=True, help_text='Page load time in milliseconds', null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When page was viewed')),
                ('church', models.ForeignKey(blank=True, help_text='Church context if church page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.church')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.visitorsession')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
