# Generated by Django 5.1.3 on 2025-10-12 17:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_analyticssettings_visitorsession_pageview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Meeting description')),
                ('room_name', models.CharField(help_text='Unique room name (3-50 characters)', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is meeting currently active?')),
                ('is_public', models.BooleanField(default=False, help_text='Can anyone join without permission?')),
                ('requires_password', models.BooleanField(default=False, help_text='Require password to join')),
                ('meeting_password', models.CharField(blank=True, help_text='Meeting password', max_length=50)),
                ('start_time', models.DateTimeField(help_text='When the meeting starts')),
                ('end_time', models.DateTimeField(help_text='When the meeting ends')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring meeting?')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='How often does this meeting repeat?', max_length=20)),
                ('allow_screen_sharing', models.BooleanField(default=True, help_text='Allow participants to share screen')),
                ('allow_recording', models.BooleanField(default=False, help_text='Allow meeting recording')),
                ('allow_chat', models.BooleanField(default=True, help_text='Enable chat during meeting')),
                ('allow_raise_hand', models.BooleanField(default=True, help_text='Allow raise hand feature')),
                ('max_participants', models.IntegerField(default=0, help_text='Maximum participants (0 = unlimited)')),
                ('lobby_enabled', models.BooleanField(default=False, help_text='Enable waiting room')),
                ('require_authentication', models.BooleanField(default=False, help_text='Require user login to join')),
                ('moderator_approval', models.BooleanField(default=False, help_text='Require moderator approval to join')),
                ('participant_count', models.IntegerField(default=0, help_text='Current number of participants')),
                ('total_participants', models.IntegerField(default=0, help_text='Total participants who joined')),
                ('meeting_duration', models.DurationField(blank=True, help_text='Total meeting duration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity in meeting')),
                ('church', models.ForeignKey(help_text='Which church this meeting belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_meetings', to='core.church')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jitsi_meetings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Associated church event (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jitsi_meetings', to='core.event')),
                ('moderators', models.ManyToManyField(blank=True, help_text='Users who can moderate this meeting', related_name='moderated_jitsi_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jitsi Meeting',
                'verbose_name_plural': 'Jitsi Meetings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='JitsiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitsi_domain', models.CharField(default='meet.jit.si', help_text='Jitsi Meet domain (use meet.jit.si for free hosting)', max_length=200)),
                ('custom_jitsi_server', models.BooleanField(default=False, help_text='Use custom Jitsi server instead of meet.jit.si')),
                ('default_meeting_duration', models.IntegerField(default=60, help_text='Default meeting duration in minutes')),
                ('default_max_participants', models.IntegerField(default=0, help_text='Default maximum participants (0 = unlimited)')),
                ('require_authentication_by_default', models.BooleanField(default=False, help_text='Require authentication by default')),
                ('enable_lobby_by_default', models.BooleanField(default=False, help_text='Enable waiting room by default')),
                ('enable_screen_sharing', models.BooleanField(default=True, help_text='Enable screen sharing by default')),
                ('enable_recording', models.BooleanField(default=False, help_text='Enable recording by default')),
                ('enable_chat', models.BooleanField(default=True, help_text='Enable chat by default')),
                ('enable_raise_hand', models.BooleanField(default=True, help_text='Enable raise hand by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(blank=True, help_text='Church-specific settings (leave blank for global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_settings', to='core.church')),
            ],
            options={
                'verbose_name': 'Jitsi Settings',
                'verbose_name_plural': 'Jitsi Settings',
            },
        ),
        migrations.CreateModel(
            name='JitsiParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name in meeting', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Participant email', max_length=254)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Time spent in meeting', null=True)),
                ('is_moderator', models.BooleanField(default=False, help_text='Is this participant a moderator?')),
                ('is_organizer', models.BooleanField(default=False, help_text='Is this participant the organizer?')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], help_text='Device used to join meeting', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='Browser used', max_length=50)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.jitsimeeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jitsi Participant',
                'verbose_name_plural': 'Jitsi Participants',
                'unique_together': {('meeting', 'user', 'joined_at')},
            },
        ),
    ]
