# Generated by Django 5.1.3 on 2025-10-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_jitsimeeting_jitsisettings_jitsiparticipant'),
    ]

    operations = [
    ]
