# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_jitsiparticipant_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Optional: external registration form (e.g. Google Form). When set, Register Now opens this URL instead of the on-page form.', null=True),
        ),
    ]
