# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_event_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamsettings',
            name='is_global_featured',
            field=models.BooleanField(default=False, help_text='Request to show this live stream on the global Watch Online page'),
        ),
        migrations.AddField(
            model_name='livestreamsettings',
            name='global_feature_status',
            field=models.CharField(
                choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='none',
                help_text='Status of request to feature on global site',
                max_length=20,
            ),
        ),
    ]
