# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_livestreamsettings_global_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamsettings',
            name='red5_stream_url',
            field=models.URLField(blank=True, help_text='Red5 stream or player embed URL'),
        ),
        migrations.AlterField(
            model_name='livestreamsettings',
            name='platform',
            field=models.CharField(
                choices=[
                    ('youtube', 'YouTube Live'),
                    ('facebook', 'Facebook Live'),
                    ('red5', 'Red5'),
                    ('instagram', 'Instagram Live'),
                    ('zoom', 'Zoom'),
                    ('other', 'Other'),
                ],
                default='youtube',
                help_text='Choose your live streaming platform',
                max_length=20,
            ),
        ),
    ]
