# Generated by Django (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_livestreamsettings_red5'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='footer_copyright',
            field=models.CharField(default='© 2025 Bethel', help_text='Footer copyright text (e.g. © 2025 Bethel)', max_length=200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='footer_links',
            field=models.JSONField(blank=True, default=list, help_text='List of footer links. Each item: {"label": "About", "url": "/about/"} or add "id": "footer-cookie-settings" for Cookie Settings.'),
        ),
    ]
