# Generated by Django 5.1.3 on 2026-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_globalsettings_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='footer_copyright',
            field=models.CharField(default='© 2026 Bethel', help_text='Footer copyright text (e.g. © 2026 Bethel)', max_length=200),
        ),
    ]
