# Generated by Django 5.1.3 on 2026-05-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='core_pushsu_church__294cbf_idx',
            old_name='core_pushsu_church__a8f2c1_idx',
        ),
    ]
