"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.
For full settings, see https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Load .env variables
load_dotenv()

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dt1#i48=k*oc^@cwtgj7v1ou(_(n%z=&omp$)fhfh3d)hvv^sg')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') + [
    '91.99.232.214',  # CyberPanel server IP
]
# Detect if running in production
USE_PROD_DB = os.environ.get('USE_PROD_DB', 'false').lower() == 'true'

# Database: PostgreSQL in production or local SQLite
if USE_PROD_DB:
    raw_db_url = os.environ.get("DATABASE_URL", "")
    if raw_db_url.startswith("postgres://"):
        raw_db_url = raw_db_url.replace("postgres://", "postgresql://", 1)

    if raw_db_url:
        try:
            DATABASES = {
                'default': dj_database_url.parse(
                    raw_db_url,
                    conn_max_age=60,  # Reduced for faster startup
                    ssl_require=True
                )
            }
            print(f"✅ Database configured: {DATABASES['default']['ENGINE']}")
        except Exception as e:
            print(f"❌ DATABASE ERROR: {e}")
            # Fallback to SQLite if database URL is invalid
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
            print("⚠️ Falling back to SQLite database")
    else:
        print("⚠️ No DATABASE_URL found, using SQLite")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Memory optimization: Database connection pooling
if USE_PROD_DB:
    DATABASES['default']['CONN_MAX_AGE'] = 60  # Reduced for faster startup
    # Add database optimizations (only valid options for PostgreSQL)
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,  # Reduced for faster startup
        'sslmode': 'require',   # Ensure SSL is required
    }
    print("🔧 Production database optimizations applied")

# Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
]

# Middleware - Optimized for production
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DatabaseIndependentMiddleware',  # Add database-independent mode
]

# URL config
ROOT_URLCONF = 'backend.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_settings',
            ],
            # Memory optimization: Disable template caching in development
            'debug': DEBUG,
        },
    },
]

# WSGI
WSGI_APPLICATION = 'backend.wsgi.application'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Localization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files with memory optimization
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/myproject/static'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Memory optimization: Use simpler static file storage
if USE_PROD_DB:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files - Local storage
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Image handling settings for better quality
THUMBNAIL_DEBUG = False
THUMBNAIL_FORCE_OVERWRITE = True
THUMBNAIL_QUALITY = 95  # High quality thumbnails
THUMBNAIL_PRESERVE_FORMAT = True

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Default PK
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS
CORS_ALLOW_ALL_ORIGINS = True

# Session settings - Extended for better user experience
if USE_PROD_DB:
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'
    SESSION_COOKIE_AGE = 86400  # 24 hours
    SESSION_SAVE_EVERY_REQUEST = True
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False
else:
    # Development session settings
    SESSION_COOKIE_AGE = 86400  # 24 hours
    SESSION_SAVE_EVERY_REQUEST = True
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Memory optimization: Cache settings (simple in-memory cache)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60,  # Reduced to 1 minute
        'OPTIONS': {
            'MAX_ENTRIES': 100,  # Reduced from 1000
        }
    }
}

# Memory optimization: Logging (reduce verbosity)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',  # Reduced from INFO
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduced from INFO
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',  # Only show database errors
            'propagate': False,
        },
    },
}

# File storage - Using local Django storage
print("Using local Django file storage")
DEFAULT_FILE_STORAGE = 'core.storage.LocalFileStorage'

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    "https://your-domain.com",
    "https://91.99.232.214",
    "http://91.99.232.214:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Memory optimization: REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # Limit page size
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Local storage initialization completed
print("Local Django file storage configured")
