from django.urls import path
from django.contrib.sitemaps.views import sitemap

from .views import (
    home, smart_home, robots_txt, events, event_detail, ministries, ministry_detail, newsletter_signup, calendar_view,
    EventListView, MinistryListView, NewsListView, NewsletterSignupCreateView, event_ics,
    about, donation, shop, watch, visit, sermon, church_list, church_detail, church_detail_by_location, church_donation,
    church_home, church_events, church_event_detail, church_ministries, church_ministry_detail,
    church_sermons, church_watch, church_news, church_about, church_calendar,
    logout_view,
    local_admin_dashboard, local_admin_events, local_admin_ministries, local_admin_news,
    local_admin_sermons, local_admin_donations, local_admin_heroes, local_admin_church_settings, local_admin_live_stream, local_admin_requests, local_admin_ministry_request_respond,
    local_admin_global_live_requests, local_admin_global_live_respond,
    local_admin_event_add, local_admin_event_edit, local_admin_event_delete, local_admin_event_bulk_delete,
    local_admin_event_hero_media, local_admin_event_speakers, local_admin_event_speaker_add, local_admin_event_speaker_edit, local_admin_event_speaker_delete,
    local_admin_event_schedule, local_admin_event_schedule_add, local_admin_event_schedule_edit, local_admin_event_schedule_delete,
    local_admin_ministry_add, local_admin_ministry_edit, local_admin_ministry_delete, local_admin_ministry_bulk_delete,
    local_admin_news_add, local_admin_news_edit, local_admin_news_delete, local_admin_news_bulk_delete,
    local_admin_sermon_add, local_admin_sermon_edit, local_admin_sermon_delete, local_admin_sermon_bulk_delete,
    local_admin_donation_edit, local_admin_donation_delete, local_admin_donation_bulk_delete, local_admin_hero_add, local_admin_hero_edit, local_admin_hero_delete,
    local_admin_users, local_admin_user_add, local_admin_user_edit, local_admin_user_change_password,
    local_admin_my_password_change,
    local_admin_mfa_security,
    local_admin_login,
    local_admin_login_verify,
    church_admin_entry,
    full_admin_home, full_admin_list, full_admin_add, full_admin_edit, full_admin_delete,
    local_admin_members, local_admin_member_add, local_admin_member_edit, local_admin_member_remove, local_admin_member_bulk_remove, local_admin_member_set_password,
    global_admin_dashboard, request_global_event_feature, global_event_feature_requests,
    request_global_hero_feature, request_global_news_feature, global_hero_feature_requests,
    global_news_feature_requests, privacy, terms, cookies, leadership, resources, testimonies, volunteer, prayer_request, contact, services,
    church_leadership, event_highlight_detail, event_speakers,
    all_event_highlights, news_detail,
    check_production_status, debug_env, test_local_upload_endpoint, upload_test_endpoint,
    health_check, startup_health_check, static_fallback, clear_redirect_notification,
    analytics_dashboard,
)
from .sitemaps import (
    StaticViewSitemap,
    ChurchSitemap,
    ChurchPagesSitemap,
    EventSitemap,
    ChurchEventSitemap,
    MinistrySitemap,
    ChurchMinistrySitemap,
    NewsSitemap,
)

_sitemaps = {
    'static': StaticViewSitemap,
    'churches': ChurchSitemap,
    'church_pages': ChurchPagesSitemap,
    'events': EventSitemap,
    'church_events': ChurchEventSitemap,
    'ministries': MinistrySitemap,
    'church_ministries': ChurchMinistrySitemap,
    'news': NewsSitemap,
}

urlpatterns = [
    path('robots.txt', robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': _sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', smart_home, name='smart_home'),  # New smart home that redirects to nearest church
    path('global/', home, name='home'),  # Global site moved to /global/
    path('events/', events, name='events'),
    path('events/calendar/', calendar_view, name='calendar'),
    path('events/<uuid:event_id>/', event_detail, name='event_detail'),
    path('events/<uuid:event_id>/register/', event_detail, name='event_registration'),
    path('events/<uuid:event_id>/add-to-calendar/', event_ics, name='event_ics'),
    path('ministries/', ministries, name='ministries'),
    path('ministries/<uuid:ministry_id>/', ministry_detail, name='ministry_detail'),
    path('news/<uuid:news_id>/', news_detail, name='news_detail'),
    path('newsletter-signup/', newsletter_signup, name='newsletter-signup'),
    # Church directory
    path('churches/', church_list, name='church_list'),
    path('churches/<str:country_slug>/<str:city_slug>/', church_detail_by_location, name='church_detail_by_location'),
    path('churches/<uuid:church_id>/', church_detail, name='church_detail'),
    path('churches/<uuid:church_id>/donate/', church_donation, name='church_donation'),
    # Church-specific website (mirrors main site functionality)
    path('church/<uuid:church_id>/', church_home, name='church_home'),
    path('church/<uuid:church_id>/events/', church_events, name='church_events'),
    path('church/<uuid:church_id>/events/<uuid:event_id>/', church_event_detail, name='church_event_detail'),
    path('church/<uuid:church_id>/ministries/', church_ministries, name='church_ministries'),
    path('church/<uuid:church_id>/ministries/<uuid:ministry_id>/', church_ministry_detail, name='church_ministry_detail'),
    path('church/<uuid:church_id>/sermons/', church_sermons, name='church_sermons'),
    path('church/<uuid:church_id>/watch/', church_watch, name='church_watch'),
    path('church/<uuid:church_id>/news/', church_news, name='church_news'),
    path('church/<uuid:church_id>/about/', church_about, name='church_about'),
    path('church/<uuid:church_id>/calendar/', church_calendar, name='church_calendar'),
    path('church/<uuid:church_id>/leadership/', church_leadership, name='church_leadership'),
    # Local Admin Dashboard (custom login with optional MFA)
    path('local-admin/login/', local_admin_login, name='local_admin_login'),
    path('local-admin/login/verify/', local_admin_login_verify, name='local_admin_login_verify'),
    path('church-admin-entry/', church_admin_entry, name='church_admin_entry'),
    path('local-admin/', local_admin_dashboard, name='local_admin_dashboard'),
    path('local-admin/full-admin/', full_admin_home, name='full_admin_home'),
    path('local-admin/full-admin/<str:app_label>/<str:model_name>/', full_admin_list, name='full_admin_list'),
    path('local-admin/full-admin/<str:app_label>/<str:model_name>/add/', full_admin_add, name='full_admin_add'),
    path('local-admin/full-admin/<str:app_label>/<str:model_name>/<str:pk>/edit/', full_admin_edit, name='full_admin_edit'),
    path('local-admin/full-admin/<str:app_label>/<str:model_name>/<str:pk>/delete/', full_admin_delete, name='full_admin_delete'),
    path('local-admin/events/', local_admin_events, name='local_admin_events'),
    path('local-admin/events/add/', local_admin_event_add, name='local_admin_event_add'),
    path('local-admin/events/<uuid:event_id>/edit/', local_admin_event_edit, name='local_admin_event_edit'),
    path('local-admin/events/<uuid:event_id>/hero-media/', local_admin_event_hero_media, name='local_admin_event_hero_media'),
    path('local-admin/events/<uuid:event_id>/speakers/', local_admin_event_speakers, name='local_admin_event_speakers'),
    path('local-admin/events/<uuid:event_id>/speakers/add/', local_admin_event_speaker_add, name='local_admin_event_speaker_add'),
    path('local-admin/events/<uuid:event_id>/speakers/<int:speaker_id>/edit/', local_admin_event_speaker_edit, name='local_admin_event_speaker_edit'),
    path('local-admin/events/<uuid:event_id>/speakers/<int:speaker_id>/delete/', local_admin_event_speaker_delete, name='local_admin_event_speaker_delete'),
    path('local-admin/events/<uuid:event_id>/schedule/', local_admin_event_schedule, name='local_admin_event_schedule'),
    path('local-admin/events/<uuid:event_id>/schedule/add/', local_admin_event_schedule_add, name='local_admin_event_schedule_add'),
    path('local-admin/events/<uuid:event_id>/schedule/<int:item_id>/edit/', local_admin_event_schedule_edit, name='local_admin_event_schedule_edit'),
    path('local-admin/events/<uuid:event_id>/schedule/<int:item_id>/delete/', local_admin_event_schedule_delete, name='local_admin_event_schedule_delete'),
    path('local-admin/events/<uuid:event_id>/delete/', local_admin_event_delete, name='local_admin_event_delete'),
    path('local-admin/events/bulk-delete/', local_admin_event_bulk_delete, name='local_admin_event_bulk_delete'),
    path('local-admin/ministries/', local_admin_ministries, name='local_admin_ministries'),
    path('local-admin/ministries/add/', local_admin_ministry_add, name='local_admin_ministry_add'),
    path('local-admin/ministries/<uuid:ministry_id>/edit/', local_admin_ministry_edit, name='local_admin_ministry_edit'),
    path('local-admin/ministries/<uuid:ministry_id>/delete/', local_admin_ministry_delete, name='local_admin_ministry_delete'),
    path('local-admin/ministries/bulk-delete/', local_admin_ministry_bulk_delete, name='local_admin_ministry_bulk_delete'),
    path('local-admin/news/', local_admin_news, name='local_admin_news'),
    path('local-admin/news/add/', local_admin_news_add, name='local_admin_news_add'),
    path('local-admin/news/<uuid:news_id>/edit/', local_admin_news_edit, name='local_admin_news_edit'),
    path('local-admin/news/<uuid:news_id>/delete/', local_admin_news_delete, name='local_admin_news_delete'),
    path('local-admin/news/bulk-delete/', local_admin_news_bulk_delete, name='local_admin_news_bulk_delete'),
    path('local-admin/sermons/', local_admin_sermons, name='local_admin_sermons'),
    path('local-admin/sermons/add/', local_admin_sermon_add, name='local_admin_sermon_add'),
    path('local-admin/sermons/<uuid:sermon_id>/edit/', local_admin_sermon_edit, name='local_admin_sermon_edit'),
    path('local-admin/sermons/<uuid:sermon_id>/delete/', local_admin_sermon_delete, name='local_admin_sermon_delete'),
    path('local-admin/sermons/bulk-delete/', local_admin_sermon_bulk_delete, name='local_admin_sermon_bulk_delete'),
    path('local-admin/donations/', local_admin_donations, name='local_admin_donations'),
    path('local-admin/donations/<uuid:method_id>/edit/', local_admin_donation_edit, name='local_admin_donation_edit'),
    path('local-admin/donations/<uuid:method_id>/delete/', local_admin_donation_delete, name='local_admin_donation_delete'),
    path('local-admin/donations/bulk-delete/', local_admin_donation_bulk_delete, name='local_admin_donation_bulk_delete'),
    path('local-admin/heroes/', local_admin_heroes, name='local_admin_heroes'),
    path('local-admin/heroes/add/', local_admin_hero_add, name='local_admin_hero_add'),
    path('local-admin/heroes/<uuid:hero_id>/edit/', local_admin_hero_edit, name='local_admin_hero_edit'),
    path('local-admin/heroes/<uuid:hero_id>/delete/', local_admin_hero_delete, name='local_admin_hero_delete'),
    path('local-admin/settings/', local_admin_church_settings, name='local_admin_church_settings'),
    path('local-admin/live-stream/', local_admin_live_stream, name='local_admin_live_stream'),
    path('local-admin/requests/', local_admin_requests, name='local_admin_requests'),
    path('local-admin/requests/<int:request_id>/respond/', local_admin_ministry_request_respond, name='local_admin_ministry_request_respond'),
    path('local-admin/global-live-requests/', local_admin_global_live_requests, name='local_admin_global_live_requests'),
    path('local-admin/global-live-requests/<uuid:settings_id>/respond/', local_admin_global_live_respond, name='local_admin_global_live_respond'),
    path('local-admin/users/', local_admin_users, name='local_admin_users'),
    path('local-admin/users/add/', local_admin_user_add, name='local_admin_user_add'),
    path('local-admin/users/<int:user_id>/edit/', local_admin_user_edit, name='local_admin_user_edit'),
    path('local-admin/users/<int:user_id>/password/', local_admin_user_change_password, name='local_admin_user_change_password'),
    path('local-admin/change-password/', local_admin_my_password_change, name='local_admin_my_password_change'),
    path('local-admin/security/', local_admin_mfa_security, name='local_admin_mfa_security'),
    path('logout/', logout_view, name='logout'),
    path('local-admin/members/', local_admin_members, name='local_admin_members'),
    path('local-admin/members/add/', local_admin_member_add, name='local_admin_member_add'),
    path('local-admin/members/<int:user_id>/edit/', local_admin_member_edit, name='local_admin_member_edit'),
    path('local-admin/members/<int:user_id>/remove/', local_admin_member_remove, name='local_admin_member_remove'),
    path('local-admin/members/bulk-remove/', local_admin_member_bulk_remove, name='local_admin_member_bulk_remove'),
    path('local-admin/members/<int:user_id>/password/', local_admin_member_set_password, name='local_admin_member_set_password'),
    path('local-admin/events/request-global-feature/<uuid:event_id>/', request_global_event_feature, name='request_global_event_feature'),
    path('local-admin/heroes/request-global-feature/<uuid:hero_id>/', request_global_hero_feature, name='request_global_hero_feature'),
    path('local-admin/news/request-global-feature/<uuid:news_id>/', request_global_news_feature, name='request_global_news_feature'),
    # Global Admin Dashboard
    path('global-admin/', global_admin_dashboard, name='global_admin_dashboard'),
    path('global-admin/event-feature-requests/', global_event_feature_requests, name='global_event_feature_requests'),
    path('global-admin/hero-feature-requests/', global_hero_feature_requests, name='global_hero_feature_requests'),
    path('global-admin/news-feature-requests/', global_news_feature_requests, name='global_news_feature_requests'),
    # Placeholder pages
    path('about/', about, name='about'),
    path('leadership/', leadership, name='leadership'),
    path('resources/', resources, name='resources'),
    path('testimonies/', testimonies, name='testimonies'),
    path('volunteer/', volunteer, name='volunteer'),
    path('prayer/', prayer_request, name='prayer_request'),
    path('contact/', contact, name='contact'),
    path('services/', services, name='services'),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),
    path('cookies/', cookies, name='cookies'),
    path('donation/', donation, name='donation'),
    path('shop/', shop, name='shop'),
    path('watch/', watch, name='watch'),
    path('visit/', visit, name='visit'),
    path('sermon/', sermon, name='sermon'),
    # API endpoints
    path('api/events/', EventListView.as_view(), name='event-list'),
    path('api/ministries/', MinistryListView.as_view(), name='ministry-list'),
    path('api/news/', NewsListView.as_view(), name='news-list'),
    path('api/newsletter-signup/', NewsletterSignupCreateView.as_view(), name='newsletter-signup-api'),
    path('events/highlight/<uuid:highlight_id>/', event_highlight_detail, name='event_highlight_detail'),
    path('events/<uuid:event_id>/speakers/', event_speakers, name='event_speakers'),
    path('events/highlights/', all_event_highlights, name='all_event_highlights'),
    # Debug views
    path('check-production-status/', check_production_status, name='check_production_status'),
    path('debug-env/', debug_env, name='debug_env'),
    path('test-imagekit-upload/', test_local_upload_endpoint, name='test_imagekit_upload'),
    path('upload-test/', upload_test_endpoint, name='upload_test'),
    path('health/', health_check, name='health_check'),
    path('startup-health/', startup_health_check, name='startup_health_check'),
    path('fallback/', static_fallback, name='static_fallback'),
    path('clear-redirect-notification/', clear_redirect_notification, name='clear_redirect_notification'),
    path('analytics/', analytics_dashboard, name='analytics_dashboard'),
]

urlpatterns += [
    # Removed debug, migration, and fix URLs
] 
